// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwyv9LPy4y5z0P0Xi7In1LUAbMQ3JVgU8',
    appId: '1:258046168427:web:c91b2c8c87df1c8e99902e',
    messagingSenderId: '258046168427',
    projectId: 'fitpal-97ceb',
    authDomain: 'fitpal-97ceb.firebaseapp.com',
    storageBucket: 'fitpal-97ceb.appspot.com',
    measurementId: 'G-YY7FCZYLH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZWdB5BUEdXX_3LYScPaKOSm6CC5zrBI',
    appId: '1:258046168427:android:0b3803e3c314489f99902e',
    messagingSenderId: '258046168427',
    projectId: 'fitpal-97ceb',
    storageBucket: 'fitpal-97ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_OLYHHGfsy1DaUiJi8rYUB5F9YRhUWQ',
    appId: '1:258046168427:ios:67c04ce47bd5217a99902e',
    messagingSenderId: '258046168427',
    projectId: 'fitpal-97ceb',
    storageBucket: 'fitpal-97ceb.appspot.com',
    iosBundleId: 'com.example.fitpal',
  );
}
