// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBux_6QJksL6XenlcC6B5GCaEwvUaY_VfQ',
    appId: '1:685952864646:web:ac12136d1f226b51199c07',
    messagingSenderId: '685952864646',
    projectId: 'fitpal-a88d8',
    authDomain: 'fitpal-a88d8.firebaseapp.com',
    storageBucket: 'fitpal-a88d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfc6GY5-fl1SUVSw0VcKRK01mMEIkZTgs',
    appId: '1:685952864646:android:0b3ec79058b9a415199c07',
    messagingSenderId: '685952864646',
    projectId: 'fitpal-a88d8',
    storageBucket: 'fitpal-a88d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWhxXmB2y2ZiwrcpnTpRkQrW1HyQTI9U',
    appId: '1:685952864646:ios:b255801b7fdcd0a1199c07',
    messagingSenderId: '685952864646',
    projectId: 'fitpal-a88d8',
    storageBucket: 'fitpal-a88d8.appspot.com',
    iosBundleId: 'com.example.fitpal',
  );
}
